language: rust
rust: stable
matrix:
  include:
    - os: osx # 10.12
      env: CGFEATURES="--features elcapitan"
    - os: osx # 10.10
      osx_image: xcode7.2
      env: CGFEATURES=""
    - os: osx # 10.13
      osx_image: xcode9.4
      env: CGFEATURES="--features highsierra,elcapitan"

script:
  - cd core-foundation
  - cargo build --verbose
  - cargo test --verbose -- --nocapture
  - cd ../core-graphics
  - cargo build --verbose $CGFEATURES
  - cargo test --verbose $CGFEATURES -- --nocapture
  - cd ../core-text
  - cargo build --verbose
  - cargo test --verbose -- --nocapture
  - cd ../cocoa
  - cargo build --verbose
  - cargo test --verbose -- --nocapture
  - cd ../io-surface
  - cargo build --verbose
  - cargo test --verbose -- --nocapture

notifications:
  webhooks: http://build.servo.org:54856/travis
