[package]
name = "cocoa"
version = "0.1.1"
authors = ["The Servo Project Developers"]
license = "MIT"

[lib]
name = "cocoa"
crate-type = ["rlib"]

[dependencies]
bitflags = "0.1"
libc = "*"
objc = "0.1"
