[package]

name = "io_surface"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[dependencies.core_foundation]

git = "https://github.com/servo/rust-core-foundation"

[dependencies.geom]

git = "https://github.com/servo/rust-geom"

[dependencies.opengles]

git = "https://github.com/servo/rust-opengles"
