[package]
name = "core-graphics"
description = "Bindings to Core Graphics for OS X"
homepage = "https://github.com/servo/core-graphics-rs"
repository = "https://github.com/servo/core-graphics-rs"
version = "0.9.1"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"

[features]
default = []
elcapitan = []

[dependencies]
bitflags = "0.9"
core-foundation = { path = "../core-foundation-rs/core-foundation" } #"0.4"
libc = "0.2"
