[package]
name = "core-text"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[dependencies]
libc = "*"

[target.x86_64-apple-darwin.dependencies]
core-foundation = "*"
core-graphics = "*"
