[package]
name = "cocoa"
description = "Bindings to Cocoa for OS X"
homepage = "https://github.com/servo/cocoa-rs"
repository = "https://github.com/servo/cocoa-rs"
version = "0.1.3"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"

[lib]
name = "cocoa"
crate-type = ["rlib"]

[dependencies]
bitflags = "*"
libc = "*"
core-graphics = "*"
objc = "0.1"
