[package]
name = "io_surface"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[dependencies.geom]
git = "https://github.com/servo/rust-geom"

[dependencies.gleam]
git = "https://github.com/servo/gleam"

[dependencies]
libc = "*"

[target.x86_64-apple-darwin.dependencies.cgl]
git = "https://github.com/servo/rust-cgl"

[target.x86_64-apple-darwin.dependencies.core_foundation]
git = "https://github.com/servo/rust-core-foundation"
